2025-03-15 20:19:40,422 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 20:19:40,454 ERROR: Error inicializando permisos: initialize_permissions() missing 1 required positional argument: 'app' [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 20:19:41,323 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 20:19:41,340 ERROR: Error inicializando permisos: initialize_permissions() missing 1 required positional argument: 'app' [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 20:19:41,985 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 20:19:42,002 ERROR: Error inicializando permisos: initialize_permissions() missing 1 required positional argument: 'app' [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 20:20:15,447 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 20:20:15,464 ERROR: Error inicializando permisos: initialize_permissions() missing 1 required positional argument: 'app' [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 20:35:06,279 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 20:35:06,322 ERROR: Error inicializando permisos: When initializing mapper Mapper[Inventory(inventory)], expression 'Document' failed to locate a name ('Document'). If this is a class name, consider adding this relationship() to the <class 'models.inventory.Inventory'> class after both dependent classes have been defined. [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 20:35:32,068 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 20:35:32,099 ERROR: Error inicializando permisos: When initializing mapper Mapper[Inventory(inventory)], expression 'Document' failed to locate a name ('Document'). If this is a class name, consider adding this relationship() to the <class 'models.inventory.Inventory'> class after both dependent classes have been defined. [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 20:56:14,040 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 20:56:14,078 ERROR: Error inicializando permisos: Could not determine join condition between parent/child tables on relationship Product.inventory_movements - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 21:01:19,415 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 21:01:19,447 ERROR: Error inicializando permisos: When initializing mapper Mapper[Inventory(inventory)], expression 'Document' failed to locate a name ('Document'). If this is a class name, consider adding this relationship() to the <class 'models.inventory.Inventory'> class after both dependent classes have been defined. [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 21:01:56,200 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 21:01:56,232 ERROR: Error inicializando permisos: When initializing mapper Mapper[Inventory(inventory)], expression 'Document' failed to locate a name ('Document'). If this is a class name, consider adding this relationship() to the <class 'models.inventory.Inventory'> class after both dependent classes have been defined. [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 21:20:09,584 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 21:20:09,630 ERROR: Error inicializando permisos: When initializing mapper Mapper[Inventory(inventory)], expression 'Document' failed to locate a name ('Document'). If this is a class name, consider adding this relationship() to the <class 'models.inventory.Inventory'> class after both dependent classes have been defined. [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 21:38:20,638 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 21:38:20,678 ERROR: Error inicializando permisos: Could not determine join condition between parent/child tables on relationship Product.inventory_movements - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 21:38:47,628 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 21:38:47,655 ERROR: Error inicializando permisos: Could not determine join condition between parent/child tables on relationship Product.inventory_movements - there are no foreign keys linking these tables.  Ensure that referencing columns are associated with a ForeignKey or ForeignKeyConstraint, or specify a 'primaryjoin' expression. [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 21:50:38,187 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 21:50:38,343 ERROR: Error inicializando permisos: (psycopg2.errors.UndefinedColumn) column permission.description does not exist
LINE 1: ...ermission_id, permission.name AS permission_name, permission...
                                                             ^

[SQL: SELECT permission.id AS permission_id, permission.name AS permission_name, permission.description AS permission_description 
FROM permission 
WHERE permission.name = %(name_1)s 
 LIMIT %(param_1)s]
[parameters: {'name_1': 'admin_access', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405) [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 21:51:08,439 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 21:51:08,554 ERROR: Error inicializando permisos: (psycopg2.errors.UndefinedColumn) column permission.description does not exist
LINE 1: ...ermission_id, permission.name AS permission_name, permission...
                                                             ^

[SQL: SELECT permission.id AS permission_id, permission.name AS permission_name, permission.description AS permission_description 
FROM permission 
WHERE permission.name = %(name_1)s 
 LIMIT %(param_1)s]
[parameters: {'name_1': 'admin_access', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405) [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 21:59:35,342 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 21:59:35,461 ERROR: Error inicializando permisos: (psycopg2.errors.UndefinedColumn) column permission.description does not exist
LINE 1: ...ermission_id, permission.name AS permission_name, permission...
                                                             ^

[SQL: SELECT permission.id AS permission_id, permission.name AS permission_name, permission.description AS permission_description 
FROM permission 
WHERE permission.name = %(name_1)s 
 LIMIT %(param_1)s]
[parameters: {'name_1': 'admin_access', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405) [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 22:07:13,917 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 22:07:14,066 ERROR: Error inicializando permisos: (psycopg2.errors.UndefinedTable) relation "permission" does not exist
LINE 2: FROM permission 
             ^

[SQL: SELECT permission.id AS permission_id, permission.name AS permission_name, permission.description AS permission_description 
FROM permission 
WHERE permission.name = %(name_1)s 
 LIMIT %(param_1)s]
[parameters: {'name_1': 'admin_access', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405) [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 22:19:56,138 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 22:19:56,161 ERROR: Error inicializando permisos: 'Engine' object has no attribute 'has_table' [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:60]
2025-03-15 22:27:04,323 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 22:27:04,426 WARNING: Permission table does not exist. Skipping permission initialization. [in /Users/mcc/Documents/Develop/backup/sgha/backend/models/user.py:127]
2025-03-15 22:27:04,426 INFO: Permisos y roles inicializados correctamente [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:58]
2025-03-15 22:27:43,722 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 22:27:43,810 WARNING: Permission table does not exist. Skipping permission initialization. [in /Users/mcc/Documents/Develop/backup/sgha/backend/models/user.py:127]
2025-03-15 22:27:43,810 INFO: Permisos y roles inicializados correctamente [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:58]
2025-03-15 22:30:06,278 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
2025-03-15 22:30:06,366 WARNING: Permission table does not exist. Skipping permission initialization. [in /Users/mcc/Documents/Develop/backup/sgha/backend/models/user.py:127]
2025-03-15 22:30:06,367 INFO: Permisos y roles inicializados correctamente [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:58]
2025-03-15 22:30:59,905 INFO: Inicio de la aplicación [in /Users/mcc/Documents/Develop/backup/sgha/backend/app.py:32]
